### ISSUE TITLE
500 Error on /callback 

### ISSUE THREAD

**Issue by Frozen-byte** [jsumners/nodebb-plugin-sso-discord-alt#16]
After authorization, I am redirected to `/auth/discord/callback` and the following error occurs:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/3965439/212881023-a8bdad30-eef7-418a-ba2e-35c8c50a825b.png">

```
2023-01-17T10:49:01.265Z [4567/4865] - error: GET /auth/discord/callback?code=aSxxxxxxxxxxxxxxxxDCw&state=Obxxxxxxxxxxxxx3k0
opt_nodebb_1  | TokenError: 
opt_nodebb_1  |     at PassportOAuth.OAuth2Strategy.parseErrorResponse (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:373:12)
opt_nodebb_1  |     at PassportOAuth.OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:420:16)
opt_nodebb_1  |     at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:177:45
opt_nodebb_1  |     at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
opt_nodebb_1  |     at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
opt_nodebb_1  |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
opt_nodebb_1  |     at IncomingMessage.emit (node:events:525:35)
opt_nodebb_1  |     at endReadableNT (node:internal/streams/readable:1359:12)
opt_nodebb_1  |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

I assume the error is on my side, still I am unable to fix it myself due to lack of an error message.

I seek assistance, finding my bug.

**Comment by gdude2002** [comment]
I can confirm that this is still an issue, even with the following versions:

- NodeBB: `4.2.1`
- Plugin: `3.0.0`

@jsumners Should we consider this plugin out-of-support?

**Comment by jsumners** [comment]
@gdude2002 yes. I haven't used NodeBB in several years, and so do not need this plugin. Feel free to fork and maintain.
