### ISSUE TITLE
Breaks NodeBB on v1.5.1

### ISSUE THREAD

**Issue by tylerstraub** [jsumners/nodebb-plugin-sso-discord-alt#6]
This plugin is not working under v1.5.1. Upon plugin activation the server crashes and will no longer start until the plugin is removed manually from NPM. 

```
20/6 22:45:46 [2215] - ^[[32minfo^[[39m: [app] Shutdown (SIGTERM/SIGINT) Initialised.
20/6 22:45:46 [2215] - ^[[32minfo^[[39m: [app] Database connection closed.
20/6 22:45:46 [2215] - ^[[32minfo^[[39m: [app] Web server closed to connections.
20/6 22:45:46 [2215] - ^[[32minfo^[[39m: [app] Shutdown complete.
[cluster] Child Process (2215) has exited (code: 0, signal: null)
20/6 22:45:46 [2403] - ^[[32minfo^[[39m: Initializing NodeBB v1.5.1
[deprecated] `String.prototype.rtrim` is deprecated as of NodeBB v1.5; use `utils.rtrim` instead.
20/6 22:45:48 [2403] - ^[[32minfo^[[39m: [socket.io] Restricting access to origin: http://strawberryunited.us:*
20/6 22:45:49 [2403] - ^[[31merror^[[39m: [plugins] filter:auth.init,  invalid sso-discord configuration
20/6 22:45:49 [2403] - ^[[31merror^[[39m:  Error: invalid sso-discord configuration
    at /home/sby/nodebb/node_modules/nodebb-plugin-sso-discord-alt/library.js:83:23
    at /home/sby/nodebb/src/meta/settings.js:13:4
    at handleCallback (/home/sby/nodebb/node_modules/mongodb/lib/utils.js:120:56)
    at /home/sby/nodebb/node_modules/mongodb/lib/collection.js:1417:5
    at handleCallback (/home/sby/nodebb/node_modules/mongodb/lib/utils.js:120:56)
    at /home/sby/nodebb/node_modules/mongodb/lib/cursor.js:682:5
    at handleCallback (/home/sby/nodebb/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/home/sby/nodebb/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /home/sby/nodebb/node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/home/sby/nodebb/node_modules/mongodb-core/lib/cursor.js:232:18)
    at /home/sby/nodebb/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[cluster] Child Process (2403) has exited (code: 0, signal: null)
```

**Comment by jsumners** [comment]
I'll take a look at it when I can, but it sounds like they changed the API.

**Comment by jsumners** [comment]
1.0.0 should resolve the problem. It will merely notify you that the configuration has not been set and skip adding the plugin as an authentication source.

**Comment by tylerstraub** [comment]
Dude, thank you @jsumners. I will give the plugin another shot here in the next week or so.
